const {LISTEPA} = require('../../app')
let myData = []  

  for(let i =0 ;i<LISTEPA.BIEN.length;i++){
    console.log(LISTEPA.BIEN[i].APPARTEMENT)

    
    myData.push(
  
    {
  
  'AFF_ID':`${LISTEPA.BIEN[i].INFO_GENERALES.AFF_ID._text}`, 
  'AFF_NUM':`${LISTEPA.BIEN[i].INFO_GENERALES.AFF_NUM._text}`, 
   'ACHAT':"",
    'LOCATION':`${LISTEPA.BIEN[i].LOCATION}`,
     'CATEGORIE_MERE' :`${LISTEPA.BIEN[i].APPARTEMENT}`, 
     'CATEGORIE':`${LISTEPA.BIEN[i].APPARTEMENT?LISTEPA.BIEN[i].APPARTEMENT.CATEGORIE._text:''}`,
     'CODE_POSTAL':`${LISTEPA.BIEN[i].LOCALISATION.CODE_POSTAL._text}`, 
     'VILLE':`${LISTEPA.BIEN[i].LOCALISATION?LISTEPA.BIEN[i].LOCALISATION.VILLE._cdata:''}`,
     'PAYS':`${LISTEPA.BIEN[i].LOCALISATION.PAYS._text}`,
     'PRIX':`${LISTEPA.BIEN[i].VENTE.PRIX._text}`,
     'LOYER':`${LISTEPA.BIEN[i].LOCATION}`,
     'CHARGES':`{${LISTEPA.BIEN[i].ALUR.CHARGES_ANNUELLES._text}}`,
     'MONTANT_HONO_ACQ':`${LISTEPA.BIEN[i].VENTE.MONTANT_HONO_ACQ}`,
     'FRAIS_AGENCE':`${LISTEPA.BIEN[i].LOCATION}`, // not exist 
     'NOM_FRANCAIS':`${LISTEPA.BIEN[i].AGENCE}`,// not exist 
     'DESCRIPTION':"",
     'LIBRELE':`{${LISTEPA.BIEN[i].INFO_GENERALES.LIBRELE._text?LISTEPA.BIEN[i].INFO_GENERALES.LIBRELE._text:''}`,
     'SURFACE_HABITABLE':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'SURFACE_TERRAIN':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'NBRE_PIECES':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'NBRE_CHAMBRES':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'NUM_ETAGE':`${LISTEPA.BIEN[i].DEMEURE}`,
     'NUM_DERNIER_ETAGE':`${LISTEPA.BIEN[i].DEMEURE}`,
     'MEUBLE':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'NBRE_SALLE_BAIN':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'NBRE_SALLE_EAU':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'NBRE_WC':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'CHAUFFAGE':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'CUISINE':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'NBRE_BALCON':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'ASCENSEUR':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'NBRE_CAVES':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'NBRE_PARKING':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'NBRE_GARAGE':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'DIGICODE':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'INTERPHONE':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'GARDIEN':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'NBRE_TERRASSE':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'ALARME':`${LISTEPA.BIEN[i].MAISON}`,
     'CALME':`${LISTEPA.BIEN[i].APPARTEMENT}`,
     'CLIMATISATION':`${LISTEPA.BIEN[i].APPARTEMENT}`,// back
     'PISCINE':`${LISTEPA.BIEN[i].MAISON}`,
     'ACCES_HANDICAPES':`${LISTEPA.BIEN[i].MAISON}`,
     'CHEMINEE':`${LISTEPA.BIEN[i].MAISON}`,
     'URL_360':"`${LISTEPA.BIEN[i].}",
     'VISITE_VIRTUELLE':`${LISTEPA.BIEN[i].INFO_GENERALES.VISITE_VIRTUELLE._cdata}`,
     'NUM_MANDAT':`${LISTEPA.BIEN[i].VENTE.NUM_MANDAT?LISTEPA.BIEN[i].VENTE.NUM_MANDAT._text:''}`,
     'AGENCE_ADRESSE':`${LISTEPA.BIEN[i].AGENCE.AGENCE_ADRESSE._cdata}`,
     'AGENCE_CP':`${LISTEPA.BIEN[i].AGENCE.AGENCE_CP._text}`,
     'AGENCE_VILLE':`${LISTEPA.BIEN[i].AGENCE.AGENCE_VILLE._cdata}`,
     'AGENCE_TELEPHONE':`${LISTEPA.BIEN[i].AGENCE.AGENCE_TELEPHONE._text}`,
     'AGENCE PORTABLE ':`${LISTEPA.BIEN[i].AGENCE.AGENCE_PORTABLE?LISTEPA.BIEN[i].AGENCE.AGENCE_PORTABLE:''}`,
     'AGENCE_NOM':`${LISTEPA.BIEN[i].AGENCE.AGENCE_NOM._cdata}`,
     'LATITUDE':"`${LISTEPA.BIEN[i].}",
     'LONGITUDE':"hello",
    }
  
    )
}
//console.log(myData);
exports.myData= myData
  