



exports.fields = ['AFF_ID', 'AFF_NUM', 'TYPE_ANNONCE',  'CATEGORIE_MERE', 'CATEGORIE','CODE_POSTAL','VILLE','PAYS','PRIX',/*'LOYER'*/,'CHARGES','MONTANT_HONO_ACQ',/*'FRAIS_AGENCE'*/,'NOM_FRANCAIS','DESCRIPTION','LIBRELE','SURFACE_HABITABLE','SURFACE_TERRAIN','NBRE_PIECES','NBRE_CHAMBRES','NUM_ETAGE','NUM_DERNIER_ETAGE','MEUBLE','NBRE_SALLE_BAIN','NBRE_SALLE_EAU','NBRE_WC','CHAUFFAGE','CUISINE','NBRE_BALCON','ASCENSEUR','NBRE_CAVES','NBRE_PARKING','NBRE_GARAGE','DIGICODE','INTERPHONE','GARDIEN','NBRE_TERRASSE','ALARME','CALME','CLIMATISATION','PISCINE','ACCES_HANDICAPES','CHEMINEE','URL_360','VISITE_VIRTUELLE','NUM_MANDAT','AGENCE_ADRESSE','AGENCE_CP','AGENCE_VILLE','AGENCE_TELEPHONE','AGENCE PORTABLE ','AGENCE_NOM','LATITUDE','LONGITUDE'];
// for(let i=0;i<fields.length;i++){
//     fields[i] = fields[i]+'!#'
//     console.log(fields[i]);
// }
// exports.fields= fields
